# Generated by Django 4.0.3 on 2022-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('package_version_code', models.CharField(max_length=100)),
            ],
        ),
    ]
